export const DIARY_EMOTIONS = [
  { id: '행복', icon: 'happy' },
  { id: '우울', icon: 'sad' },
  { id: '신남', icon: 'exciting' },
  { id: '분노', icon: 'angry' },
  { id: '피곤함', icon: 'tired' },
  { id: '놀람', icon: 'surprise' },
  { id: '슬픔', icon: 'cry' },
  { id: '불안', icon: 'nervous' },
  { id: '외로움', icon: 'alone' },
  { id: '무기력', icon: 'lethargy' },
  { id: '기쁨', icon: 'glad' },
  { id: '설렘', icon: 'funny' },
  { id: '감동', icon: 'touched' },
  { id: '짜증', icon: 'annoy' },
  { id: '후회', icon: 'regret' },
  { id: '당황', icon: 'embrassed' },
  { id: '긴장', icon: 'tension' },
  { id: '지루함', icon: 'boring' },
  { id: '실망', icon: 'disappoint' },
  { id: '평온', icon: 'peace' },
] as const;

export type EmotionId = (typeof DIARY_EMOTIONS)[number]['id'];
export type ReactionCounts = Record<EmotionId, number>;

export const DIARY_COUNT: ReactionCounts = {
  행복: 0,
  우울: 0,
  신남: 0,
  분노: 0,
  피곤함: 0,
  놀람: 0,
  슬픔: 0,
  불안: 0,
  외로움: 0,
  무기력: 0,
  기쁨: 0,
  설렘: 0,
  감동: 0,
  짜증: 0,
  후회: 0,
  당황: 0,
  긴장: 0,
  지루함: 0,
  실망: 0,
  평온: 0,
};
